
### end-to-end argument  {.smaller}


* Saltzer, Reed, Clark, ‘‘End-to-End Arguments in System Design’’
* ‘‘The function in question can completely and correctly be implemented  only with the knowledge and help of the application standing at the end points of the communication system. Therefore, providing that questioned function as a feature of the communication system itself is not possible. (Sometimes  an incomplete version of the function provided by the communication system may be useful as a performance enhancement.)’’


### againframe(endToEndStatement)

### example: reliable file transfer  {.smaller}


* want to make sure correct data transferred .5cm
* want to protect against: 

   * error in hardware/software on sending machine reading file
   * bits being flipped in memory on forwarding machine
   * communication system flipping bits in data
   * hosts crashing during communication
 .5cm
* \it communication system can't help a lot of these things
* \it authors experienced router with bad memory/processor


### solution: end-to-end checks 


* want reliable transfer: compare final files (with hash or similar) .5cm
* ‘‘end-to-end'’ --- doesn’t care what middle systems do


### againframe(endToEndStatement)

### end-to-end in practice  {.smaller}


* ‘‘narrow waist'’ of IP doesn’t provide many gaurnetees 

   * no gaurentees about reliable transmission, duplicate suppression, message order, \ldots

* but try to provide good service (‘‘best effort’’) .5cm
* in design: typically middle systems won't know/care about what's forwarded 

   * but many exceptions


