
### some challenges for streams  {.smaller}



* separating data into pieces network can handle
* putting pieces back together
* getting network to send piece to correct remote network
* getting network to send piece to correct machine
* getting machine to send data to correct program
* getting pieces into format wires/radio/fiber/etc. can handle
* handling transmission errors

::: {.myoverbox .fragment fragment-index=1 .fade-in-then-out .vlow}

lots of work! don't want to implement all at once!

:::

::: {.myoverbox .fragment fragment-index=2 .fade-in-then-out .vlow}

some parts need to be different for different local networks

:::

::: {.myoverbox .fragment fragment-index=3 .fade-in-then-out .vlow}

some parts should not concern local network implementors

:::

::: {.myoverbox .fragment fragment-index=4 .fade-in-then-out .vlow}

some parts should be same for different abstraction

:::


### layered model


* networking implemented in ‘layers’
* upper layers implemented by making calls to lower layers
<hr class="vspace" />
* example: network implements ‘send data to (remote) machine’ function (‘‘network layer’’)
* stream implementation calls this to implement ‘send stream to remote application’

