
# routing problem {visibility="hidden"}

{{< include /routing/_route-tables.qmd >}}

# actions on forwarding {visibility="hidden"}

{{< include /routing/_forward-act.qmd >}}

## unreachable {visibility="hidden"}

### againframe(forwardProbs)

{{< include /routing/_unreachable.qmd >}}

## fragmentation, MTUs {visibility="hidden"}

### againframe(forwardProbs)

{{< include /routing/_fragments.qmd >}}

## exercise{visibility="hidden"}

{{< include /routing/_frag-perf-ex.qmd >}}

## time-to-live {visibility="hidden"}

### againframe(forwardProbs)

{{< include /routing/_ttl.qmd >}}

# traceroute {visibility="hidden"}

{{< include /routing/_traceroute.qmd >}}

# centralized versus distributed {visibility="hidden"}

{{< include /routing/_central-v-dist.qmd >}}

# basic flooding / MAC learning {visibility="hidden"}

{{< include /routing/_basic-flooding.qmd >}}

# spanning trees {visibility="hidden"}

{{< include /routing/_spanning-tree.qmd >}}

# preview: better routing {visibility="hidden"}

{{< include /routing/_preview-better.qmd >}}

# aside: metrics {visibility="hidden"}

{{< include /routing/_metrics.qmd >}}

# Bellman-Ford {visibility="hidden"}

{{< include /routing/_bellman-ford.qmd >}}

# distance vector routing {visibility="hidden"}

## distributing Bellman-Ford {visibility="hidden"}

{{< include /routing/_bellman-ford-dist.qmd >}}

## aside: networks and routers {visibility="hidden"}

{{< include /routing/_network-v-router-dv.qmd >}}

## algorithm {visibility="hidden"}

{{< include /routing/_dv-algo.qmd >}}

## RIP {visibility="hidden"}

{{< include /routing/_rip-protocol.qmd >}}

## handling removal {visibility="hidden"}

{{< include /routing/_removalp.qmd >}}

## count-to-infinity {visibility="hidden"}

{{< include /routing/_count-to-infty.qmd >}}

# link state {visibility="hidden"}

## idea {visibility="hidden"}

{{< include /routing/_link-state-idea.qmd >}}

## link state advertisements {visibility="hidden"}

{{< include /routing/_link-state-adv.qmd >}}

## link state database {visibility="hidden"}

{{< include /routing/_link-state-db.qmd >}}

## reliable flooding {visibility="hidden"}

{{< include /routing/_ls-reliable-flood.qmd >}}

## shortest path first {visibility="hidden"}

{{< include /routing/_ls-shortest-path.qmd >}}

## shortest path algorithm {visibility="hidden"}

{{< include /routing/_bestFirstExample.qmd >}}

## shortest path consistency {visibility="hidden"}

{{< include /routing/_sp-consistency.qmd >}}

## convergence {visibility="hidden"}

{{< include /routing/_ls-v-dv-converge.qmd >}}

## networks versus routers {visibility="hidden"}

{{< include /routing/_network-v-router-ls.qmd >}}

# multipath/load balancing {visibility="hidden"}

{{< include /routing/_multipath.qmd >}}

# scalability: OSPF areas {visibility="hidden"}

## motivation / basic idea {visibility="hidden"}

{{< include /routing/_area-big-net.qmd >}}

## areas are DV {visibility="hidden"}

{{< include /routing/_area-is-dv.qmd >}}

## always route through backbone {visibility="hidden"}

{{< include /routing/_ospf-backbone.qmd >}}

# interdomain routing {visibility="hidden"}

{{< include /routing/_interdomain-problems.qmd >}}

## terminology: autonomous system {visibility="hidden"}

{{< include /routing/_define-as.qmd >}}

## relationship types {visibility="hidden"}

{{< include /routing/_relate-types.qmd >}}

## aside: connecting big networks {visibility="hidden"}

{{< include /routing/_aside-connect-big.qmd >}}

## local/remote preferences {visibility="hidden"}

{{< include /routing/_distant-prefs.qmd >}}

## sharing routes: BGP {visibility="hidden"}

{{< include /routing/_bgp-overview.qmd >}}

## BGP route format {visibility="hidden"}

{{< include /routing/_bgp-route-format.qmd >}}

## sharing routes: picture {visibility="hidden"}

{{< include /routing/_bgp-basic-picture.qmd >}}

## sharing routes: multiple connections {visibility="hidden"}

{{< include /routing/_bgp-simple-multi.qmd >}}

## BGP route preference order {visibility="hidden"}

{{< include /routing/_bgp-route-pref.qmd >}}

# UVa, in practice {visibility="hidden"}

{{< include /routing/_in-practice-uva.qmd >}}

## internet exchanges, peeringdb {visibility="hidden"}

{{< include /routing/_peeringdb-ixp.qmd >}}

## BGP communities {visibility="hidden"}

{{< include /routing/_bgp-comm.qmd >}}

## BGP hijacking/fat fingers {visibility="hidden"}

{{< include /routing/_hijack.qmd >}}

## validating routes / sBGP {visibility="hidden"}

{{< include /routing/_aside-verification.qmd >}}

## aside: partial tables {visibility="hidden"}

{{< include /routing/_partial-tables.qmd >}}
