
### virtual time

* easier to compute _number of rounds_ than _number of steps_
* so we'll compute a "_virtual time_" = round number
  * "virtual clock" that advanced at variable speed
  * X flows $\rightarrow$ virtual clock goes 1/X as fast
* use virtual times to sort packets

### computing virtual time  {.smaller}



* sending [A1 (2 bit)]{.fragment fragment-index=2 .custom .myem-only}, [A2 (1 bit)]{.fragment fragment-index=3 .custom .myem-only}, [B1 (4 bit)]{.fragment fragment-index=4 .custom .myem-only}, [B2 (1 bit)]{.fragment fragment-index=5 .custom .myem-only}, [C1 (2 bit)]{.fragment fragment-index=6 .custom .myem-only}
* ‘current’ virtual time = 0
  * current time = round # a packet sent now would start transmitting
 

<table class="collines">
<thead>
<tr><th>packet</th><th>virtual finish time</th>
</thead>
<tbody>
<tr class="fragment fade-in" data-fragment-index="2"><td>A1</td><td>2 (= current + size)</td>
<tr class="fragment fade-in" data-fragment-index="3"><td>A2</td><td>3 (= A1's time + size)</td>
<tr class="fragment fade-in" data-fragment-index="4"><td>B1</td><td>4 (= current + size)</td>
<tr class="fragment fade-in" data-fragment-index="5"><td>B2</td><td>5 (= B1's time + size)</td>
<tr class="fragment fade-in" data-fragment-index="6"><td>C1</td><td>2 (= current + size)</td>
</tbody>
</table>

* virtual time = time for packet alone + max {last finish time from flow, current time}


### late packets {.smaller}

sending A1 (2 bit), B1 (2 bit), B2 (2 bit) <br> and A2 (2 bit) but that arrives between steps 5+6: 


::::: {.columns}


:::: {.column}

<table class="collines">
<thead>
<tr><th>vtime</th><th>step</th><th>action</th></tr>
</thead>
<tbody>
<tr><td>1</td><td>1</td><td>send A1 bit 1</td></tr>
<tr><td>1</td><td>2</td><td>send B1 bit 1</td></tr>
<tr><td>2</td><td>3</td><td>send A1 bit 2</td></tr>
<tr><td>2</td><td>4</td><td>send B1 bit 2</td></tr>
<tr><td>3</td><td>5</td><td>send B2 bit 1</td></tr>
<tr><td>4</td><td>&mdash;</td><td>(get A2)</td></tr>
<tr><td>4</td><td>6</td><td>send A2 bit 1</td></tr>
<tr><td>4</td><td>7</td><td>send B2 bit 1</td></tr>
<tr><td>5</td><td>8</td><td>send A2 bit 1</td></tr>
<tr><td>6</td><td>9</td><td>send A2 bit 1</td></tr>
</tbody>
</table>


::::


:::: {.column}

<table class="collines">
<thead>
<tr><th>packet</th><th>virtual finish time</th></tr>
</thead>
<tbody>
<tr class="fragment fade-in" data-fragment-index="2"><td>A1</td><td>2 (= current + size)</td></tr>
<tr class="fragment fade-in" data-fragment-index="3"><td>B1</td><td>2 (= current + size)</td></tr>
<tr class="fragment fade-in" data-fragment-index="4"><td>B2</td><td>4 (= B1's time + size)</td></tr>
<tr class="fragment fade-in" data-fragment-index="5"><td>A2 [late]</td><td>5 (= current AKA 3 + size)</td></tr>
</tbody>
</table>

::::

:::::

