
# recall: window size versus bandwidth {visibility="hidden"}

{{< include /reliable-window/_window-size-empirical-graph.qmd >}}

{{< include /reliable-window/_window-size-empirical.qmd >}}

# why optimal / counting packets in flight {visibility="hidden"}

{{< include /congest-intro/_window-optimum.qmd >}}

# searching for performance {visibility="hidden"}

{{< include /congest-intro/_find-window.qmd >}}

# a little history {visibility="hidden"}

{{< include /congest-intro/_collapse-history.qmd >}}

### fixes from Jacobson's 1987 paper 

1.  round-trip-time variance estimation
2.  exponential retransmit timer backoff
3.  slow-start
4.  more aggressive receiver ack policy
5.  dynamic window sizing on congestion
6.  Karn's clamped retransmit backoff
7.  fast retransmit


# performance collapse {visibility="hidden"}

{{< include /congest-intro/_overload.qmd >}}

# changing cross-traffic {visibility="hidden"}

{{< include /congest-intro/_cross-traffic.qmd >}}

# up/down pattern (rough) {visibility="hidden"}

{{< include /congest-intro/_window-change-rough.qmd >}}

# heuristic: slow increase {visibility="hidden"}

{{< include /congest-intro/_heuristic-increase.qmd >}}

## exercise: convergence times {visibility="hidden"}

{{< include /congest-intro/_convergence-time.qmd >}}

# heuristic: fast decrease (v1) {visibility="hidden"}

{{< include /congest-intro/_heuristic-decrease-to-1.qmd >}}

# original TCP congestion control {visibility="hidden"}

{{< include /congest-intro/_tcp-tahoe-intro.qmd >}}

# sawtooth pattern {visibility="hidden"}

{{< include /congest-intro/_sawtooth.qmd >}}

# aside: examining congestion control on Linux {visibility="hidden"}

{{< include /congest-intro/_linux-ss.qmd >}}

# part 1: window sizing {visibility="hidden"}

# focus on steady state {visibility="hidden"}

{{< include /congest-intro/_focus-steady-state.qmd >}}

### fixes from Jacobson's 1987 paper 

1.  round-trip-time variance estimation
2.  exponential retransmit timer backoff
3.  slow-start
4.  more aggressive receiver ack policy
5.  _dynamic window sizing on congestion_
6.  Karn's clamped retransmit backoff
7.  _fast retransmit_

# revised TCP congestion control {visibility="hidden"}

{{< include /congest-intro/_tcp-reno-intro.qmd >}}

# heuristic: fast decrease (v2) {visibility="hidden"}

{{< include /congest-intro/_heuristic-decrease.qmd >}}

# AIMD {visibility="hidden"}

{{< include /congest-intro/_aimd.qmd >}}

# some graphs {visibility="hidden"}

{{< include /congest-intro/_tcp-normal-graphs.qmd >}}

## exercise: non-congestion losses {visibility="hidden"}

{{< include /congest-intro/_non-congest-losses.qmd >}}
