
### why optimal  {.smaller}

* window size $\sim$ number of packets in flight
* in normal operation with window size $W$ 
   * receive ACK for $x$ (now $W-1$ in flight)
   * send packet $x+W$
   * receive ACK for $x+1$
   * send packet $x+W+1$
   * …
* window size keeps $W$ packets in flight
   * increase window = more packets in flight
   * decrease window = reduce packets in flight
* ideal choice $\sim$ amount network can handle

### number in flight on losses  {.smaller}

* window size $W$
* let's say we lose packet $x$ [only], sender might 

   * receive ACK for $x-1$
   * send packet $x+W-1$
   * receive ACK for $x$, $x$, $x$, …
   * resend packet $x$ (guess it is lost)
   * [receive ACK for $x$, $x$, $x$, …]{.fragment fragment-index=2 .custom .myem-only}
   * receive ACK for packet $x+W-1$
   * send packets $x+W$ through $x+W+W-1$

::: {.myoverbox .low .fragment}

*  lots of time when we are not sending packets
*  means links are underutilized

:::

### window size tweaking 


* window size imperfect proxy for # packets in flight
* we'll ignore the difference for now 
<hr class="vspace" />
* our goal for now: window size = number of packets to have in flight

