
### P4: control plane


* P4 control plane is a program 
<hr class="vspace" />
* sends commands to one or more switches: 

   * load P4 program into data plane
   * set table entries
   * configure multicast groups
   * receive frames to process them



### aside: wrappers  {.smaller}


* I'll show code from a P4 controller for upcoming assignment
* written in Python, using custom library to make things convenient
* works with softawre based reference switch 
<hr class="vspace" />
* no requirement to use Python or other specific language 

   * controller sends commands over network/IPC to data plane

* real raw code has more boilerplate/etc.
* probably several things different for hardware-based switches



### P4: control plane


* P4 control plane is a program 
<hr class="vspace" />
* sends commands to one or more switches: 

   * _load P4 program into data plane_
   * set table entries
   * configure multicast groups
   * receive frames to process them

### P4: loading P4 program

    
<pre><code>p4info_helper =  ....
switch = ....
<span data-fragment-index="2" class="fragment custom myem-only">switch.MasterArbitrationUpdate()</span>
switch.<span data-fragment-index="3" class="fragment custom myem-only">SetForwardingPipelineConfig</span>(
    p4info=p4info_helper.p4info,
    <span data-fragment-index="4" class="fragment custom myem-only">bmv2_json_file_path=bmv2_file_path</span>
)
</code></pre>

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=2}

* switch supports having primary + backup controller
* need to indicate that this program is primary controller now

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=3}

"forwarding pipeline" = dataplane

:::


::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=4}

P4 code compiled to file to load, specified by `bmv2_json_file_path` option

:::


### P4: control plane


* P4 control plane is a program 
<hr class="vspace" />
* sends commands to one or more switches: 

   * load P4 program into data plane
   * _set table entries_
   * configure multicast groups
   * receive frames to process them

### P4: setting table entries 

    
<pre><code><span data-fragment-index="5" class="fragment custom myem-only">write_or_overwrite_table_entry</span>(
    <span data-fragment-index="2" class="fragment custom myem-only">p4info_helper=p4info_helper, switch=switch,</span>
    table_name='<span data-fragment-index="3" class="fragment custom myem-only">MyIngress.mac_dst_exact</span>',
    match_fields={
        'hdr.ethernet.dstAddr': <span data-fragment-index="4" class="fragment custom myem-only">some_address</span>,
    },
    action_name='forward_to',
    action_params={'port': port},
)
</code></pre>

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=2}

p4info\_helper, switch objects created by setup code

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=3}

*  full name of table includes stage it is defined in
*  (this example: _MyIngress._mac\_dst\_exact)

:::


::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=4}

*  `match_fields` specifies key to set
*  format would be different if `lpm` or `ternary` instead of `exact` match

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=5}

*  `write_or_overwrite_table_entry` is not the "raw" function
    *  (I wrote it based on P4 tutorial authors' version)

:::


### P4: control plane


* P4 control plane is a program 
<hr class="vspace" />
* sends commands to one or more switches: 

   * load P4 program into data plane
   * set table entries
   * _configure multicast groups_
   * receive frames to process them

### P4: multicast groups

    
<pre><code>switch.Write<span data-fragment-index="4" class="fragment custom myem-only">PRE</span>Entry(
    p4info_helper.buildMulticastGroupEntry(
        <span data-fragment-index="2" class="fragment custom myem-only">multicast_group_id=1</span>, 
        <span data-fragment-index="3" class="fragment custom myem-only">replicas</span>=[
            {'egress_port': 1, 'instance': 0},
            {'egress_port': 2, 'instance': 0},
            {'egress_port': 3, 'instance': 0},
            {'egress_port': 4, 'instance': 0},
        ]
    )
)
</code></pre>

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=2}

in P4 dataplane code can write<br/>
`stndard_metadata.mcast_grp = 1` to use this

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=3}

*  `replicas` = list of ports to output to

*  `instance` values can be inspected by egress dataplane code

:::


::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=4}


*  PRE = packet replication engine

*  supports multicast groups (shown) and "clone sessions" (not shown)
   *  clone sessions make extra copy of packet but keep original

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=5}

*  `write_or_overwrite_table_entry` is not the "raw" function
    *  (I wrote it based on P4 tutorial authors' version)

:::


### P4: control plane


* P4 control plane is a program 
<hr class="vspace" />
* sends commands to one or more switches: 

   * load P4 program into data plane
   * set table entries
   * configure multicast groups
   * _receive frames to process them_

### P4: receiving frame 

    
<pre><code>    for item in switch.stream_msg_resp:
        if item.HasField('packet'):
            do_something_with(<span data-fragment-index="2" class="fragment custom myem-only">item.packet.payload</span>,
                              <span data-fragment-index="3" class="fragment custom myem-only">item.packet.metadata</span>)
</code></pre>

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=2}

*  payload = bytes of frame
   *  (what would be sent on network)

:::

::: {.myoverbox .low .fragment .fade-in-then-out fragment-index=3}

*  extra "metadata" can be set by dataplane
   *  example: which port packet came in from

:::
