
### P4: ingress processing  {.smaller}

    

* example: send <i>everything</i> to output port number 4
 
<pre><code>control MyIngress(...) {
    apply {
        <span data-fragment-index="1" class="fragment custom myem-only">standard_metadata.egress_spec = 4;</span>
    }
}
</code></pre>

::: {.myoverbox .fragment fragment-index=1 .low}

*  standard\_metadata --- "hard-coded" phase reads `egress_spec`
*  special `egress_spec` value for "discard frame"

:::


### switch decisions  {.smaller}


* most decisions switches/routers make are table lookups 
<hr class="vspace" />
* take field from packet (e.g. destination)
* lookup in table what to do with that (e.g. send to port X, throw error, etc.) 
<hr class="vspace" />
* P4 has special syntax for tables and table lookups


### P4: tables

    
<pre><code><span data-fragment-index="2" class="fragment custom myem-only">table</span> mac_dst_exact {
    <span data-fragment-index="3" class="fragment custom myem-only">key</span> = {
        <span data-fragment-index="3" class="fragment custom myem-only">hdr.ethernet.dstAddr</span> : <span data-fragment-index="4" class="fragment custom myem-only">exact</span>;
    }
    <span data-fragment-index="3" class="fragment custom myem-only">actions</span> = {
        drop,
        forward_to,
    }
    size = 1024;
    default_action = drop();
}
</code></pre>

::: {.myoverbox .midright .fragment fragment-index=2 .fade-in-then-out}

*  declare a table wtih a name
*  done as part of ingress/egress

:::

::: {.myoverbox .midright .fragment fragment-index=3 .fade-in-then-out}

* key/value structure
* keys usually from headers
* values are the actions to run

:::

::: {.myoverbox .midright .fragment fragment-index=4 .fade-in-then-out}

* here, each table entry<br/>contains whole address

* P4 also supports partially matched keys

:::


### P4 table key types  {.smaller}


* exact --- full entry
* lpm --- longest prefix match 

   * table entries contain ‘prefixes’ of header field(s)
   * we'll see motivation for this when we talk about routing
   * if multiple entries match, take longest one

* ternary --- 0/1/don't care 

   * table entries contain key and mask
   * entry matches if bits included in mask match
   * other view: keys represented with 0/1/don't care ‘trits’



### content-addressable memory  {.smaller}


* high-end routers/switches have <i>content addressable memory</i> (CAM)
* … including <i>ternary content addressable memory</i> (TCAM) 
<hr class="vspace" />
* = hardware that implements a table lookup 

   * ‘content’ $\approx$ key being looked up
   * looks kinda like highly associative cache
   * probably lots of comparators

* allows multigigabit frame processing speeds
* P4 goal: P4 programs compile to use CAM/TCAM when available


### aside: TCAM cost  {.smaller}


* 2.7x more transistors than SRAM (common cache technology)
* probably much more power than SRAM
* hard to find recent quotes for price/power
* but probably 10s of dollars per megabyte 

   * e.g., secondary market price of Broadcom chip with 40Mbit of this is $\sim$\$180
   * chip needs 80W heatsink, max 900MHz clock rate
   * but chip has a bunch of other functionality, of course



### P4: using a table  

    
<pre><code>control MyIngress(...) {
    ...
    table mac_dst_exact = { 
        /* seen earlier */ ...
    }
    apply {
        <span data-fragment-index="2" class="fragment custom myem-only">mac_dst_exact.apply();</span>
    }
}
</code></pre>

::: {.myoverbox .midright .fragment fragment-index=2}

apply operation invokes the action specified

:::


### P4: actions  {.smaller}

    
<pre><code>control MyIngress(...) {
    <span data-fragment-index="2" class="fragment custom myem-only">action drop()</span> {
        mark_to_drop(<span data-fragment-index="3" class="fragment custom myem-only">standard_metadata</span>);
    }
    <span data-fragment-index="2" class="fragment custom myem-only">action forward_to(egressSpec_t port)</span> {
        <span data-fragment-index="3" class="fragment custom myem-only">standard_metadata.egress_spec = port;</span>
    }
    <span data-fragment-index="2" class="fragment custom myem-only">action mark_and_forward(egressSpec_t port)</span> {
        <span data-fragment-index="4" class="fragment custom myem-only">hdr.some_proto.value</span> = 1;
        <span data-fragment-index="3" class="fragment custom myem-only">standard_metadata.egress_spec = port;</span>
    }
    ...
}
</code></pre>

::: {.myoverbox .midright .fade-in-then-out .fragment fragment-index=2}

*  actions basically function calls for pacekt

*  can include parameters that are stored in table

:::

::: {.myoverbox .midright .fade-in-then-out .fragment fragment-index=3}

typically actions set standard\_metdata <br/>
to indicate where to send frame next

:::

::: {.myoverbox .midright .fade-in-then-out .fragment fragment-index=4}

actions can also edit packet headers <br/>
or do other table lookups

:::


### P4: special actions  {.smaller}


* some ways switch can direct packet (incomplete list) 
<hr class="vspace" />
* send to the control plane 

   * special output port that goes to ‘general purpose’ CPU

* multicast/broadcast to multiple ports 

   * control plane can set <i>multicast groups</i>
   * makes multiple copies of packets


