
### P4: declaring headers (1)  {.smaller}

    
<pre><code>typedef bit&lt;48&gt; macAddr_t;
<span data-fragment-index="0" class="fragment custom myem-only">@header</span> ethernet_t {
    macAddr_t srcAddr;
    macAddr_T dstAddr;
    bit&lt;16&gt;   etherType;
}
</code></pre>
 

* kinda like `typedef struct { ... } ethernet_t;`
* order needs to <i>exactly</i> match what's sent on network 

   * switch will do bit-by-bit copy into this struct



### P4: declaring headers (2)  {.smaller}

    
<pre><code><span data-fragment-index="0" class="fragment custom myem-only">struct headers</span> {
    <span data-fragment-index="1" class="fragment custom myem-only">ethernet_t</span>   ethernet;
    <span data-fragment-index="1" class="fragment custom myem-only">ipv4_t</span>       ipv4;
    <span data-fragment-index="1" class="fragment custom myem-only">ipv6_t</span>       ipv6;
}
</code></pre>
 

* struct of all possible headers 

   * from all layers the switch/router handles
   * not all frames will use all of them, some may be mutually exclusive
   * order does not need to match frame storage (will write code to handle that)

* references header types defined previously


### P4: parsing  {.smaller}


```
parser MyParser(
    packet_in packet,
    out headers hdr,
    inout metadata meta,
    inout standard_metadata_t standard_metadata) {

```
 

* function modifies ‘out’ parameters instead of returning
* parser function --- takes parameters: 

   * packet --- the input frame
   * headers --- extracted headers (<code>struct headers</code>)
   * meta --- program's local variables about frame (<code>struct metadata</code>)
   * standard_metadata --- info for system about frame 

      * where frame came from, where it should go, etc.




### P4: parsing

    
<pre><code>parser MyParser(...) {
    <span data-fragment-index="2" class="fragment custom myem-only">state</span> start {
        <span data-fragment-index="3" class="fragment custom myem-only">transition</span> <span data-fragment-index="3" class="fragment custom myem-only">parse_ethernet</span>;
    }
    <span data-fragment-index="2" class="fragment custom myem-only">state</span> <span data-fragment-index="3" class="fragment custom myem-only">parse_ethernet</span> {
        <span data-fragment-index="4" class="fragment custom myem-only">packet.extract(hdr.ethernet);</span>
        <span data-fragment-index="3" class="fragment custom myem-only">transition</span> select(hdr.ethernet.etherType) {
            TYPE_IPV4: parse_ipv4;
            TYPE_IPV6: parse_ipv6
            default: accept;
        }
    }
    ....
}
</code></pre>

::: {.myoverbox .fragment .fade-in-then-out .midright fragment-index=2}

*  functions written as state machine

*  execution starts in state `start`

*  follows instructions in each state

:::

::: {.myoverbox .fragment .fade-in-then-out .low fragment-index=3}

* transition statements say which state next

* can be conditional using switch-statement-like syntax

:::


::: {.myoverbox .fragment .fade-in-then-out .midright fragment-index=4}

`extract` operation copies from packet<br/>into specifiec `header` object

:::

