### transmission errors {.smaller}

*  problem: transmitting symbols has some errors
*  bad cable, radio interference, mismatched clocks, ...
<hr class="vspace"/>
*  will get frames with incorrect data
*  will get frames with missing/extra data from misdetecting start/end markers
*  could pass "bogus" frames to next layer, but...
*  better to detect this quickly

### checksum idea  {.smaller}


* instead of sending ‘‘message’’
<hr class="vspace"/>
* say Hash(‘‘message’’) = 0xABCDEF12
* then send ‘‘0xABCDEF12,message’’
  <hr class="vpsace"/>
* when receiving, recompute hash
* discard message if checksum doesn't match


### checksum functions  {.smaller}


* hashes used to check messages called checksums
* used at data link layer and upper layers 

   * lots of places networks want to check messages aren't corrupted
 .5cm
* provides high probability we discard corrupted messages 

   * larger checksum $\rightarrow$ higher probability



### example common checksums  {.smaller}


* IPv4, TCP --- 

   * based on one's complement sum of data+metadata treated as 16-bit numbers
   * one's complement addition = add normally with wraparound + add carry bit at end
   * efficient to implement on processor with addition
   * easy to compute incrementally

* Ethernet 

   * 32-bit ‘‘cyclic redundancy code’’
   * easy to compute fast in hardware
   * always detects up to 3 bits flipped (for sizes used in Ethernet)



### beyond checksums 


* checksums detect errors pretty reliably...
* by sending extra bits
<hr class="vspace"/>
* sending extra bits can also correct some errors pretty reliably
* ‘‘error correcting code’’ 
   * efficient ways to do this? covered in ECE/CS 4434
* very common for wireless

