### last time {.smaller}

*  physical layer options
   *  vary something(s) over time
   *  one "symbol" per time-step
   *  need to have common clock between sender/receiver
*  framing --- dividing symbols into messages ("frames")
   *  escaping and/or extra "control" symbols
*  checksums to catch errors (with high probability)
*  acknowledgment + retransmissions
   *  stop + wait protocol
   *  1-bit sequence numbers if no reordering
*  wireshark example

### assignment notes

*  implementing stop/wait in simulator
*  `from_application`:
   *  called to give you data from application layer
   *  you return if you can accept it
   *  (since you can't just loop + sleep until you can send it)
*  timeouts
   *  since simulated time, need to use our timer functions

### assignment Q+A

## some examples in wireshark {visibility="hidden"}

{{< include /intro/_wireshark-ex.qmd >}}

# interlude: metrics {visibility="hidden"}

{{< include /perf/_talk-inner.qmd >}}

### stop-and-wait issues 


* two issues with stop-and-wait: 
<hr class="vspace" />
* doesn't use close to full capacity of network
* not clear how to set timeouts


### looking at metrics  {.smaller}


* several important metrics we'll care about
* (both for this and future topics) 
<hr class="vspace" />
* <i>throughput</i> and <i>bandwidth</i> ($\sim$ how much capacity used/available)
* <i>latency</i> and <i>round-trip time</i> (RTT) ($\sim$ what timeouts needed)
* <i>jitter</i> ($\sim$ safety margin for timeouts)

{{< include /reliable-stop/_stop-and-wait-perf.qmd >}}

{{< include /reliable-window/_talk-inner.qmd >}}

{{< include /reliable-tcp/_talk-inner.qmd >}}

