### last time {.smaller}

*  P4 tables
   *  keys from parsed header items
   *  fixed, longest-prefix, ternary (don't care bits) matching
*  P4 actions
*  P4 controller
*  MAC learning
*  IPv4, v6 header
*  IP addresses

### quiz

### on loops in P4 parsers

*  P4 basically says loops could create compile-time/runtime errors
   *  especially if not bounded by consuming part of packet
*  "header stack" feature that is better at bounding
   *  fixed-size array of subheaders
*  my guesses as to reasons for this
   *  want to bound packet processing times
   *  support switch architectures which do packet processing with long (hardware) pipelines where loops need to be unrolled into similar-looking pipeline stages

### assignment Q+A

## CIDR notation{visibility="hidden"}

{{< include /arp/_ipv4-cidr.qmd >}}

## IPv6 {visibility="hidden"}

{{< include /arp/_ipv6.qmd >}}

## address space allocation {visibility="hidden"}

{{< include /arp/_ip-iana.qmd >}}

## which link-local addresses {visibility="hidden"}

{{< include /arp/_disamb-link-local.qmd >}}

# routing versus switching {visibility="hidden"}

{{< include /arp/_route-v-switch-table.qmd >}}

{{< include /arp/_routing-v-switching.qmd >}}

# ARP {visibility="hidden"}

## neighbor table, filling by hand {visibility="hidden"}

{{< include /arp/_make-ntable.qmd >}}

## ARP, ND {visibility="hidden"}

{{< include /arp/_protocols.qmd >}}

## what if there are two {visibility="hidden"}

{{< include /arp/_dup-address.qmd >}}

## ARP hijacking {visibility="hidden"}

{{< include /arp/_arp-hijack.qmd >}}

# exercise {visibility="hidden"}

{{< include /arp/_ip-mac-exer.qmd >}}

# DHCP {visibility="hidden"}

{{< include /arp/_dhcp.qmd >}}

## DHCP relays {visibility="hidden"}

{{< include /arp/_dhcp-relay.qmd >}}

## DHCPv6 {visibility="hidden"}

# IPv6 autoconfiguration {visibility="hidden"}

{{< include /arp/_ipv6-autoconf.qmd >}}

{{< include /congest-intro/_talk-inner.qmd >}}

###

# backup slides

# IP packet format {visibility="hidden"}

{{< include /arp/_ip-format.qmd >}}

