
### normal packets in flight  {.smaller}

 <table>
<tr><td>recv'd</td><td>sent</td><td>count of packets in flight</td></tr>
<tr><td><!-- \hline --> ---</td><td>data 0-7</td><td>8</td></tr>
<tr><td>ACK 0</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 8</td><td>8</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 9</td><td>8</td></tr>
<tr><td>ACK 2</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 10</td><td>8</td></tr>
<tr><td>ACK 3</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 11</td><td>8</td></tr>
<tr><td>ACK 4</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 12</td><td>8</td></tr>
</table>
  

* window size $\sim$ packets in flight normally


### duplicate ACK waste  {.smaller}



* window size $\sim$ packets in flight normally
* but duplicate ACKs are exception (say window size 8)
  <table style="font-size: 80%">
<tr><td>recv'd</td><td>sent</td><td>count of packets in flight</td></tr>
<tr><td><!-- \hline --> ---</td><td>data 0-7</td><td>8</td></tr>
<tr><td>ACK 0</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 8</td><td>8</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>&nbsp;</td><td>data 9</td><td>8</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>7</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>6</td></tr>
<tr><td>&nbsp;</td><td>data 2</td><td>5</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>4</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>3</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>2</td></tr>
</table>
  

* problem: need to wait until ACK of 2 to make progress


### alternate explanation  {.smaller}


* sender stopped sending while receiving duplicate ACKs
* but we know <i>most messages got there</i>
* means our usage of network doesn't reflect our window size 
<hr class="vspace" />
* want to transmit new packets in response to these ACKs 

   * even though out of ‘normal’ window



### TCP's fast recovery  {.smaller}


* estimate <i>packets in flight</i> 

   * with no losses, <code>cwnd</code> already does this!
   * problem: needs adjustment there are losses

* transmit new packets when packets in flight \< cwnd 

   * two implementation ideas:
   * temporarily ‘inflate’ cwnd
   * track effective send window separately



### fast recovery example  {.smaller}

 <table style="font-size: 70%">
<tr><td>recv'd</td><td>sent</td><td>est. packets in flight</td><td>send window size (range)</td><td>cwnd = target packets in flight</td></tr>
<tr><td><!-- \hline --> ---</td><td>data 0-7</td><td>8</td><td>8 (0-7)</td><td>8</td></tr>
<tr><td>ACK 0</td><td>&nbsp;</td><td>7</td><td>8 (0-7)</td><td>8</td></tr>
<tr><td>&nbsp;</td><td>data 8</td><td>8</td><td>8 (1-8)</td><td>8</td></tr>
<tr><td>ACK 1</td><td>&nbsp;</td><td>7</td><td>8 (1-8)</td><td>8</td></tr>
<tr><td>&nbsp;</td><td>data 9</td><td>8</td><td>8 (2-9)</td><td>8</td></tr>
<tr><td>ACK 1 (+3)</td><td>&nbsp;</td><td>7</td><td>8 (2-9)</td><td>8</td></tr>
<tr><td>ACK 1 (+3-4)</td><td>&nbsp;</td><td>6</td><td>8 (2-9)</td><td>8</td></tr>
<tr><td>ACK 1 (+3-5)</td><td>&nbsp;</td><td>5</td><td>8 (2-9)</td><td>4</td></tr>
<tr><td>&nbsp;</td><td>data 2</td><td>6</td><td>8 (2-9)</td><td>4</td></tr>
<tr><td>ACK 1 (+3-6)</td><td>&nbsp;</td><td>5</td><td>8 (2-9)</td><td>4</td></tr>
<tr><td>ACK 1 (+3-7)</td><td>&nbsp;</td><td>4</td><td>8 (2-9)</td><td>4</td></tr>
<tr><td>ACK 1 (+3-8)</td><td>&nbsp;</td><td>3</td><td>8 (2-9)</td><td>4</td></tr>
<tr><td>&nbsp;</td><td>data 10</td><td>4</td><td>9 (2-10)</td><td>4</td></tr>
<tr><td>ACK 1 (+3-9)</td><td>&nbsp;</td><td>3</td><td>9 (2-10)</td><td>4</td></tr>
<tr><td>&nbsp;</td><td>data 11</td><td>4</td><td>10 (2-11)</td><td>4</td></tr>
<tr><td></td></tr>
</table>
  

* during recovery, ‘‘inflate’’ effective send window size
* try to make actual packets in flight match new congestion window size

