
# ‘slow start’ {visibility="hidden"}

### fixes from Jacobson's 1987 paper 

1.  round-trip-time variance estimation
2.  exponential retransmit timer backoff
3.  _slow-start_
4.  more aggressive receiver ack policy
5.  dynamic window sizing on congestion
6.  Karn's clamped retransmit backoff
7.  fast retransmit


{{< include /congest-opt/_slow-start.qmd >}}

## exercise {visibility="hidden"}

{{< include /congest-opt/_slow-start-ex.qmd >}}

# original TCP congestion control (restated) {visibility="hidden"}

{{< include /congest-opt/_tcp-tahoe.qmd >}}

# original TCP congestion control (restated) {visibility="hidden"}

{{< include /congest-opt/_tcp-reno.qmd >}}

## some more graphs {visibility="hidden"}

## repeated graph{visibility="hidden"}

{{< include /congest-intro/_tcp-normal-graphs.qmd >}}

## non-repeated graph{visibility="hidden"}

{{< include /congest-opt/_graphs-with-slow-start.qmd >}}

# ‘fast retransmit’ and ‘fast recovery’ {visibility="hidden"}

### fixes from Jacobson's 1987 paper 

1.  round-trip-time variance estimation
2.  exponential retransmit timer backoff
3.  slow-start
4.  more aggressive receiver ack policy
5.  dynamic window sizing on congestion
6.  Karn's clamped retransmit backoff
7.  _fast retransmit_

### TCP (New)Reno [with slow start]  {.smaller}


* <i>congestion avoidance</i> (cwnd $\ge$ ssthresh; no known loss) 

   * no loss: cwnd += 1 segment per round-trip-time
   * on loss (dup ACK): cwnd = cwnd/2; ssthresh = new cwnd
   * on loss (timeout): cwnd = 2 segments

* <i>‘‘slow start’’</i> (cwnd \< ssthresh) 

   * no loss: cwnd += 1 segment per newly ack'd segment
   * on loss: ssthresh = cwnd/2; cwnd = cwnd/2;

* <i>recovery</i> (known loss) 

   * _resend immediately on third dup ACK_
   * send new data based on self-clocking idea (‘‘fast recovery’’)


## recall: duplicate ACKs {visibility="hidden"}

{{< include /reliable-window/_dup-ack-opt.qmd >}}

## duplicate ACKs {visibility="hidden"}

{{< include /congest-opt/_dup-ack-window.qmd >}}

### TCP (New)Reno [with slow start]  {.smaller}


* <i>congestion avoidance</i> (cwnd $\ge$ ssthresh; no known loss) 

   * no loss: cwnd += 1 segment per round-trip-time
   * on loss (dup ACK): cwnd = cwnd/2; ssthresh = new cwnd
   * on loss (timeout): cwnd = 2 segments

* <i>‘‘slow start’’</i> (cwnd \< ssthresh) 

   * no loss: cwnd += 1 segment per newly ack'd segment
   * on loss: ssthresh = cwnd/2; cwnd = cwnd/2;

* <i>recovery</i> (known loss) 

   * resend immediately on third dup ACK
   * _send new data based on self-clocking idea (‘‘fast recovery’’)_


## self-clocking and fast retransmit {visibility="hidden"}

{{< include /congest-opt/_self-clock-idea.qmd >}}

## SACK {visibility="hidden"}

{{< include /congest-opt/_sack.qmd >}}

# missing piece: reverse path {visibility="hidden"}

{{< include /congest-opt/_reverse-path.qmd >}}

# aside: some queuing theory {visibility="hidden"}

{{< include /congest-opt/_diversion-queuing-theory.qmd >}}

# deep queues? {visibility="hidden"}

{{< include /congest-opt/_buffer-bloat.qmd >}}

# missing Jacobson pieces {visibility="hidden"}

## variance estimation {visibility="hidden"}

### againframe(jacobsonFixes)

{{< include /congest-opt/_variance-estimate.qmd >}}

## exponential backoff {visibility="hidden"}

### againframe(jacobsonFixes)

{{< include /congest-opt/_exp-backoff.qmd >}}

# TCP variants {visibility="hidden"}

{{< include /congest-opt/_tcp-variant-names.qmd >}}

## CUBIC {visibility="hidden"}

{{< include /congest-opt/_cubic.qmd >}}

# other congestion signals {visibility="hidden"}

{{< include /congest-opt/_other-signals.qmd >}}

## explicit congestion notification {visibility="hidden"}

### againframe(otherSig)

{{< include /congest-opt/_ecn.qmd >}}

## watching latency, etc. {visibility="hidden"}

### againframe(otherSig)

{{< include /congest-opt/_watch-latency.qmd >}}

# overall congestion control data {visibility="hidden"}

{{< include /congest-opt/_overall-data.qmd >}}
