### last time {.smaller}

*  buffer bloat
*  CUBIC --- better fast exploration/slow adjustment compromise
*  rate-/latency-based congestion control
   *  latency increases if queuing increases
   *  Vegas: compare latency to "optimal" latency, adjust window accordingly
   *  bandwidth stays same if queuing increases
   *  BBR: measure ACK rate to infer bandwidth
*  unfairness of FIFO+drop-tail
*  fair queuing
   *  round-robin baseline
   *  estimating bit-by-bit round-robin

### assignment Q+A

###


{{< include /queuing/_fair-queue-alt-bit.qmd >}}

## fair dequeue: virtual time {visibility="hidden"}

{{< include /queuing/_virtual-time-intro.qmd >}}

{{< include /queuing/_virtual-time.qmd >}}

## fair queuing and late packets {visibility="hidden"}

{{< include /queuing/_fq-and-late.qmd >}}

## fair dequeue: weighted fair queuing {visibility="hidden"}

{{< include /queuing/_weighted-fair-queue.qmd >}}

## exercise {visibility="hidden"}

{{< include /queuing/_weighted-fair-queue-ex.qmd >}}

## weighted fair queuing practice {visibility="hidden"}

{{< include /queuing/_weighted-fair-queue-practice.qmd >}}

# priority queuing {visibility="hidden"}

{{< include /queuing/_priority-queue.qmd >}}

# drop-tail: unfair discard {visibility="hidden"}

{{< include /queuing/_drop-tail-unfair-discard.qmd >}}

# drop-tail: long wait {visibility="hidden"}

{{< include /queuing/_drop-tail-long-wait.qmd >}}

# early detection {visibility="hidden"}

{{< include /queuing/_early-detect.qmd >}}

## some results {visibility="hidden"}

{{< include /queuing/_early-detect-res.qmd >}}

# active queue management generally {visibility="hidden"}

{{< include /queuing/_other-queue-management.qmd >}}

{{< include /routing-intro/_talk-inner.qmd >}}
