# routing problem {visibility="hidden"}

{{< include /routing-intro/_route-tables.qmd >}}

# actions on forwarding {visibility="hidden"}

### problems when forwarding 

* no entry in routing table
* no entry in neighbor table
   * (after attempting ARP, or neighbor discovery)
* packet too big for next network
* there's an infinite loop in the route

## unreachable {visibility="hidden"}

### problems when forwarding 

* _no entry in routing table_
* _no entry in neighbor table_
   * (after attempting ARP, or neighbor discovery)
* packet too big for next network
* there's an infinite loop in the route


{{< include /routing-intro/_unreachable.qmd >}}

## fragmentation, MTUs {visibility="hidden"}

### problems when forwarding 

* no entry in routing table
* no entry in neighbor table
   * (after attempting ARP, or neighbor discovery)
* _packet too big for next network_
* there's an infinite loop in the route

{{< include /routing-intro/_fragments.qmd >}}

## exercise{visibility="hidden"}

{{< include /routing-intro/_frag-perf-ex.qmd >}}

## time-to-live {visibility="hidden"}

### problems when forwarding 

* no entry in routing table
* no entry in neighbor table
   * (after attempting ARP, or neighbor discovery)
* packet too big for next network
* _there's an infinite loop in the route_

{{< include /routing-intro/_ttl.qmd >}}

# traceroute {visibility="hidden"}

{{< include /routing-intro/_traceroute.qmd >}}

# centralized versus distributed {visibility="hidden"}

{{< include /routing-intro/_central-v-dist.qmd >}}

# basic flooding / MAC learning {visibility="hidden"}

<!-- FIXME: cleanup diagrams -->

{{< include /routing-intro/_basic-flooding.qmd >}}

# spanning trees {visibility="hidden"}

{{< include /routing-intro/_spanning-tree.qmd >}}

# preview: better routing {visibility="hidden"}

{{< include /routing-intro/_preview-better.qmd >}}

# aside: metrics {visibility="hidden"}

{{< include /routing-intro/_metrics.qmd >}}
