
### destination host unreachable  {.smaller}


```
$ ping 128.143.67.254
PING 128.143.67.254 (128.143.67.254) 56(84) bytes of data.
From 128.143.63.1 icmp_seq=1 Destination Host Unreachable
From 128.143.63.1 icmp_seq=6 Destination Host Unreachable
^C
--- 128.143.67.254 ping statistics ---
10 packets transmitted, 0 received, +2 errors, 100% packet loss, time 9146ms
pipe 4

```
<hr/>
```
$ ping6 2606:8e80:7007:ef1a::1
PING 2606:8e80:7007:ef1a::1(2606:8e80:7007:ef1a::1) 56 data bytes
From 2606:8e80:7007:ef1a:cf1f:3948:b5c1:a522 icmp_seq=1
        Destination unreachable: Address unreachable
....

```


### ICMPv6 destination unreachable messages  {.smaller}


* IPv6 header with ICMP as next protocol
* 1 byte type = 1 (destination unreachable)
* 1 byte code = 

   * examples: address unreachable, administritatively prohibited

* most of contents of message causing problem 

   * only most to avoid exceeding max packet size
   * should let OS figure out which socket to send error to



### generating destination unreachable  {.smaller}


* by routers: reached correct network, machine not there
* by routers: no route to network at all
* by routers: administrator rule prohibits forwarding
* by destination host: no program listening to that ‘port’
* … 
<hr class="vspace" />
* different code values for all cases
* machine can also choose to send nothing back


### ICMPv4 destination unrachable 


* basically same format as ICMPv6, but…
* different type/code integer values
* only IPv4 header + 64 bytes of original packet included

